default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: base_tolls_dev

test:
  <<: *default
  database: base_tolls_test

production:
  <<: *default
  database: base_tools_prod
